# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test_setup.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='test_setup.proto',
  package='testsetup',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10test_setup.proto\x12\ttestsetup\"\x0e\n\x0c\x45mptyRequest\"\x1b\n\x08Response\x12\x0f\n\x07message\x18\x01 \x01(\t2F\n\tTestSetup\x12\x39\n\x07Request\x12\x17.testsetup.EmptyRequest\x1a\x13.testsetup.Response\"\x00\x62\x06proto3'
)




_EMPTYREQUEST = _descriptor.Descriptor(
  name='EmptyRequest',
  full_name='testsetup.EmptyRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=45,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='testsetup.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='testsetup.Response.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=74,
)

DESCRIPTOR.message_types_by_name['EmptyRequest'] = _EMPTYREQUEST
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EmptyRequest = _reflection.GeneratedProtocolMessageType('EmptyRequest', (_message.Message,), {
  'DESCRIPTOR' : _EMPTYREQUEST,
  '__module__' : 'test_setup_pb2'
  # @@protoc_insertion_point(class_scope:testsetup.EmptyRequest)
  })
_sym_db.RegisterMessage(EmptyRequest)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'test_setup_pb2'
  # @@protoc_insertion_point(class_scope:testsetup.Response)
  })
_sym_db.RegisterMessage(Response)



_TESTSETUP = _descriptor.ServiceDescriptor(
  name='TestSetup',
  full_name='testsetup.TestSetup',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=76,
  serialized_end=146,
  methods=[
  _descriptor.MethodDescriptor(
    name='Request',
    full_name='testsetup.TestSetup.Request',
    index=0,
    containing_service=None,
    input_type=_EMPTYREQUEST,
    output_type=_RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_TESTSETUP)

DESCRIPTOR.services_by_name['TestSetup'] = _TESTSETUP

# @@protoc_insertion_point(module_scope)
